### ISSUE TITLE
Thunderbird 91 compatibility

### ISSUE THREAD

**Issue by 3rd3** [jdede/WarnAttachment#13]
It would be awesome if this attachment would run on TB 91. For me it shows as incompatible on the Add-ons for Thunderbird page ("Works with Thunderbird 68.0 - 89.0").

**Comment by jdede** [comment]
Thanks for the hint. Just pushed a new version to addons.thunderbird.net. Should be available soon.
Issue fixed by e44d5dac617167e3e060705df5f8b11825dbc721
