### ISSUE TITLE
Ideas for default block list

### ISSUE THREAD

**Issue by 3rd3** [jdede/WarnAttachment#15]
[This article](https://sensorstechforum.com/popular-windows-file-types-used-malware-2018/) mentions various potentially dangerous suffixes. Some of these might be worth adding:

> .exe, .msi, .msp, .com, .gadget, .cmd, .vbe, .jse, .ps1, .ps1xml, .ps2, .ps2xml, .psc1, .psc2, .lnk, .inf, .scf, .hta, .html, .htm, .js, .jar, .vbs, .vb, .sfx, .bat, .dll, .tmp, .py, .shadow, .djvu, .djvur, .djvuu, .udjvu, .uudjvu, .djvuq, .djvus, .djvur, .djvut, .pdff, .tro, .tfude, .tfudet, .tfudeq, .rumba, .adobe, .adobee, .blower, .promos, .promoz, .promorad, .promock, .promok, .promorad2, .kroput, .kroput1, .pulsar1, .kropun1, .charck, .klope, .kropun, .charcl, .doples, .luces, .luceq, .chech, .proden, .drume, .tronas, .trosak, .grovas, .grovat, .roland, .refols, .raldug, .etols, .guvara, .browec, .norvas, .moresa, .vorasto, .hrosas, .kiratos, .todarius, .hofos, .roldat, .dutan, .sarut, .fedasot, .berost, .forasom, .fordan, .codnat, .codnat1, .bufas, .dotmap, .radman, .ferosas, .rectot, .skymap, .mogera, .rezuc, .stone, .redmat, .lanset, .davda, .poret, .pidom, .pidon, .heroset, .boston, .muslat, .gerosan, .vesad, .horon, .neras, .truke, .dalle, .lotep, .nusar, .litar, .besub, .cezor, .lokas, .godes, .budak, .vusad, .herad, .berosuce, .gehad, .gusau, .madek, .darus, .tocue, .lapoi, .todar, .dodoc, .bopador, .novasof, .ntuseg, .ndarod, .access, .format, .nelasod, .mogranos, .cosakos, .nvetud, .lotej, .kovasoh, .prandel, .zatrov, .masok, .brusaf, .londec, .krusop, .mtogas, .nasoh, .nacro, .pedro, .nuksus, .vesrato, .masodas, .cetori, .stare, .carote, .gero, .hese, .seto, .peta, .moka, .kvag, .karl, .nesa, .noos, .kuub, .reco, .bora, .reig, .tirp, .plam, .cosd, .ygkz, .cadq, .ribd, .qlkm, .coos, .wbxd, .pola

**Comment by jdede** [comment]
These are dynamic and changing extensions. Adding them makes no sense. Maybe one could implement something like an automatic updater which fetches the file extensions from a website. For that, something like a REST API would be nice. It should offer the current malicious extension as a web service.
Nevertheless, the risk of false positives is increasing with those extensions. So I prefer not adding all those dynamic extensions.
