### ISSUE TITLE
New functionality

### ISSUE THREAD

**Issue by bilbostiff** [jdede/WarnAttachment#18]
Hello i was trying to implement a new function of the plugin but i can't do it. I want to check, before sending a message, if there are any attachments and if so check if all attachments have an .asc or .gpg extension or any (because the options), and if any of them do not have one of these two extensions to display a warning to the user such as "Warning: the following attachments appear to be unencrypted. Are you sure you want to continue (SEND / CANCEL)". If the files have all of these extensions or if there are no attachments, there is no need to display a popup. Could you do it or show me how can i do it? Thank you!!

**Comment by bilbostiff** [comment]
I had tried so many times but i don't understand 100% the code, because i'm noob on JS. Please if you can, help me ;)

**Comment by jdede** [comment]
Hm, I think that this should be

a) implemented directly in TB
b) a separate plug-in

Unfortunately, I do not have the time to work on such a project. Sorry for that.
