### ISSUE TITLE
Check and adapt for tb 115+

### ISSUE THREAD

**Issue by jdede** [jdede/WarnAttachment#20]
Tested the add-on with the current beta (115) and it seems not to work: No messages are shown. Maybe we have to get rid of the experiment.
Maybe @arai-a can check or has more information what has to be done?

**Comment by arai-a** [comment]
opened https://github.com/jdede/WarnAttachment/pull/21 which fixes the previous PR,
and also opened https://github.com/jdede/WarnAttachment/pull/22 which updates the code for https://bugzilla.mozilla.org/show_bug.cgi?id=1696777 change

**Comment by jdede** [comment]
closed by #22 and #21
