### ISSUE TITLE
Thunderbird 68 compatibility

### ISSUE THREAD

**Issue by beerisgood** [jdede/WarnAttachment#3]
Sadly your addon isn't compatible with latest Thunderbird

**Comment by jdede** [comment]
I know and I have checked the necessary changes today. I hope that I will be able to fix it within the next two to three weeks.

**Comment by wazzza13** [comment]
How is it going with addon?

**Comment by jdede** [comment]
Unfortunately, it takes more time than expected. Still working on it.

**Comment by jdede** [comment]
I have created a branch for the TB 68 changes (tb_68.x) and pushed kind of a first beta release: https://github.com/jdede/WarnAttachment/blob/tb_68.x/bin/warnattachment-1.0.xpi
The 1.x does not mean that it is a stable release, but it is incompatible with the earlier versions 0.x.
If you have some time it would be nice if you could test the new version and give me some feedback.

Thanks a lot

**Comment by wazzza13** [comment]
Add-on is working. Rules are correctly regulated. Thunderbird version 68.1.2

**Comment by jdede** [comment]
Thanks for the feedback. I am still waiting for two more feedbacks and will try to publish it tomorrow.

**Comment by beerisgood** [comment]
I can it test tomorrow when I'm back from work if you want another Feedback then

**Comment by jdede** [comment]
@beerisgood thanks. If you find the time, it would be nice if you could check.

I just pushed a new version with some minor changes:
https://github.com/jdede/WarnAttachment/blob/tb_68.x/bin/warnattachment-1.1.xpi

Thanks for supporting me.

**Comment by jdede** [comment]
And another version: https://github.com/jdede/WarnAttachment/blob/tb_68.x/bin/warnattachment-1.2.xpi

**Comment by jdede** [comment]
Will merge the branch to master and push to ATN today. Hope that it will be available in the next days for an automatic update.

**Comment by beerisgood** [comment]
> 
> 
> @beerisgood thanks. If you find the time, it would be nice if you could check.
> 
I had now time to test and it looks good!

**Comment by jdede** [comment]
Thank you for your feedback, @beerisgood . Uploaded the new version to ATN. Currently, it is queued in position 6. Depending on the speed of the review team, the add-on should be available within the next 24 - 48 hours.

**Comment by jdede** [comment]
A brief update: Since Friday in position 2 of the queue. I am still waiting for the Add-On version to get accepted and published.

**Comment by jdede** [comment]
Finally, the new version is online.
Thank you for your support!
