### ISSUE TITLE
Thunderbird 78.x and higher (webextensions?) compatibility?

### ISSUE THREAD

**Issue by subscribernamegoeshere** [jdede/WarnAttachment#7]
Hello developer team,

any chance of any speedy support for Thunderbird 78.x new extensions and addons mechanism, maybe called webextensions or whatnot. Unfortunately Mozilla keeps up bumping and changing APIs and structures too often and making a lot of experiments.

Any infos on 78+ compat and eta? Really appreciate this addon and piece of software for Thunderbird. For the noobs and masses this is really a security measure and a last line of defence.

Thanks again!

**Comment by beerisgood** [comment]
As workaround (and even much better solution):
Use SRP so you can't open dangerous attachments. Hard_Configurator from AndyFul is a easy way to do that

**Comment by jdede** [comment]
Dear @subscribernamegoeshere ,
as you said: the update are quite complex. The API for the configuration storage is not available till now and has to be implemented as a custom API. Not a big deal, but it takes time. I will do it as soon as possible, but it will last some weeks.

@beerisgood , the SRP solution is (AFAIK) only available for Windows systems. Main objective is, to offer an add-on running on all major OSs.

Best regards
Jens

**Comment by jdede** [comment]
Fixed in Version 2.x 5f399111289ab4e5d947787d9b8f140c5198b453
