### ISSUE TITLE
WA 2.1 . .eml attachment files (mails inside mails e.g. via forwards) render all attachments unusable after the first attachment handling

### ISSUE THREAD

**Issue by subscribernamegoeshere** [jdede/WarnAttachment#8]
Hi there developer folks,

I was very happy to see warnattachment 2.1 show up for thunderbird. Just dicovered some nasty stuff with it? Tested on 64bit Thunderbird 78.5.0 (windows) but also had some other 75.8.0 32bit on windows as well.

Situation:

sending very simple e.g. text-only mail, to myself, pop3 or imap account inside TB.

1. write simple mail to yourself
2. receive mail with TB and WA (2.1) addon installed
3. forward this email as attachment (.eml file being created in attachment area) to yourself again
4. receive email again via pop3/imap
5. open this email with an email embedded as attachment/.eml inside
6. click onto the .eml in the attachment area in the gui, or the email icon in the attachment area
7. this brings up the forwarded attached email in a new TB window. so far so good.
8. close this window again
9. try to work and use your TB again, for example just try to re-open this .eml/attached email object again

10. result: nothing happens ever again after this step 9, regarding attachment functions.

meaning: i can not make the .eml/forwarded email attached to open again
I also can not open any other type of attachments ever again after this step, so for example my other emails with e.g. say very simple stuff .pdf attached in them. I can not double click on those PDF attachments, I can not rightclick on the .pdf attachment there and make it appear/show/start the default PDF app etc..

only the very first attachment type of handling event  seems to work in TB from now on.

Shutting down TB and restarting it, brings back functionality, for attachments, but exactly only for ONE attachment/event after that again.

Every second and follwing attempt to work/read/open/execute attachment objects apparently leads to no event being executed.

Its not that the TB gui is being blocked or hanging or anything. TB gui seems to be fine. Also no pending notification or popups are being seen, or no modal dialog boxes are blocking anything.

As far as I can tell.

Something is becoming stuck or blocked or something after the very first attachment event. I can tell for sure this happens when you start with .eml/attached-mails type of attachments. Thats how some friends of mine reported back to me today that TB was broken or something was seriously wrong.

When simple disabling WA inside the addons-area (blue lever) the functionality returns.

Also .eml attachment are obviously NOT inside any warned or blocked attachment type in WA settings. Nor are e.g. PDF or anything.

Its about completely unblocked, unwarned attachment types.

Thats at least as far as I can tell in this bugreport.
Please look into this quickly if possible. Thank you!

**Comment by subscribernamegoeshere** [comment]
p.s. apparently there are even other peple observing this behaviour talking about it on AMO ATO in their reviews of WA

https://addons.thunderbird.net/de/thunderbird/addon/warnattachment/reviews/
quoting: MX_EH: In version 2.1 there's a bug related to opening files with the EML extension. It allows you to open it once, but then there're problems opening any files whose extensions aren't defined in the options.......
> https://addons.thunderbird.net/thunderbird/addon/warnattachment/reviews/1164760/

**Comment by jdede** [comment]
Thank you for your report. Can you please check if this version works for you:

https://github.com/jdede/WarnAttachment/blob/master/bin/warnattachment-2.2.xpi

Best regards
Jens

**Comment by subscribernamegoeshere** [comment]
Hi there, odd enough, that .xpi URL I can not make any use of. What downloads there seems as if it was a html/xml page. And to my knowledge so far .xpi files were like some zip-like container file.

Just compared from the addons thunderbird page the older 2.1 version .xpi
https://addons.thunderbird.net/thunderbird/downloads/latest/warnattachment/addon-811161-latest.xpi?src=dp-btn-primary

with the 2.1 xpi link here on github in the bin folder, but which is also a html like file there and even the older 2.1 working .xpi from addons tb, I can not use the binary .xpi from github here?

whats wrong with the binary downloads here:
https://github.com/jdede/WarnAttachment/tree/master/bin

I tried the last two ones to dragdrop or to load from the tb addon area load addon from file. both fail with red exclamation mark error claiming that these two .xpi are corrupt and nonworking files?

**Comment by subscribernamegoeshere** [comment]
I am stupid it seems... ;) It was only a pre-page on github, I had thought those were the actual .xpi files, I always rightclick and saved them. but that is another github page, and there is the "view raw"... function, and only that is the actual .xpi payload. So this 2.2 now loads fine into TB on windows. will check

**Comment by subscribernamegoeshere** [comment]
Okay just tested this 2.2 xpi file on windows, in 64bit TB 78.5.0
.eml files seem to work fine now, WA 2.2 also seems to permanently work now, I can navigate across my emails and open other e.g. PDF attachments from mails or image/jpg attachments and so on.

Nothing seems stuck any more. I say give it a go for WA 2.2 and publish on the AMO site. Thank you again!

**Comment by subscribernamegoeshere** [comment]
Tested some more, with for example warned attachment types, forwarding them back and forth, generating .eml files and attachments within attachments e.g. .doc file inside .eml file, inside mail

seems to work nicely. no more functionality loss or blocking of attachment events. thanks.

**Comment by jdede** [comment]
Thanks a lot for your feedback. Just uploaded the file to AMO, hopefully it will be online soon. So c35234bdb90f4b95f765e01eca5f90ef38ddf456 fixes the bug.

**Comment by subscribernamegoeshere** [comment]
the WA 2.2 update just appeared on the addons mozilla mechanism.

**Comment by subscribernamegoeshere** [comment]
seems to be the proper 2.2 release just as tested some hours go from here on github. functionality seems to work now with eml files. thanks for the speedy repair of this bug.
